# -*- coding: utf-8 -*-

"""
/***************************************************************************
 PipelineEngineer
                                 A QGIS plugin
 A collection of Pipeline Engineering Tools.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-06
        copyright            : (C) 2025 by Pipeline Engineer
        email                : info@pipelineengineer.com.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Pipeline Engineer'
__date__ = '2025-12-06'
__copyright__ = '(C) 2025 by Pipeline Engineer'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis import processing

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (
    QgsProcessing,
    QgsFeatureSink,
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterField,
    QgsFeatureRequest,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterNumber,
    QgsProcessingParameterVectorLayer,
    QgsProcessingParameterMultipleLayers,
    QgsProcessingParameterEnum,
    QgsProcessingOutputString,
    QgsProcessingException,
    QgsProcessingOutputMultipleLayers,
    QgsProcessingParameterFileDestination,
    QgsProcessingParameterString,
    QgsProcessingParameterRasterLayer
)

from PyQt5.QtCore import QCoreApplication

from .logic.correct_directionality import *
from .logic.run_beggs_brill_pipeflow import *

class BeggsBrillNetworkSkeleton(QgsProcessingAlgorithm):

    NETWORK_LAYER = 'NETWORK_LAYER'
    RASTER = 'RASTER'
    CHAINAGE = 'CHAINAGE'
    LOAD_LAYERS = 'LOAD_LAYERS'
    OUTPUT = 'OUTPUT'

    def initAlgorithm(self, config):

        # Input line layer
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.NETWORK_LAYER,
                self.tr('Select Pipe Result Layer'),
                [QgsProcessing.TypeVectorLine]
            )
        )

        # Input raster layer
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.RASTER,
                self.tr('Select Raster Layer')
            )
        )
        
        self.addParameter(
            QgsProcessingParameterNumber(
                self.CHAINAGE, 'Chainage',
                type=QgsProcessingParameterNumber.Double,
                minValue=0, maxValue=100000, defaultValue=20
            )
        )

        self.addParameter(QgsProcessingParameterBoolean(
            self.LOAD_LAYERS, 'Load Layers?',
            defaultValue=True
        ))

        # Output: list of layer IDs
        self.addParameter(QgsProcessingParameterFileDestination(
                self.OUTPUT,
                'Output GeoPackage',
                fileFilter='GeoPackage (*.gpkg)'
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        
        pipe_results_layer = self.parameterAsVectorLayer(parameters, self.NETWORK_LAYER, context)

        chainage = self.parameterAsDouble(parameters, self.CHAINAGE, context)

        raster_layer = self.parameterAsRasterLayer(parameters, self.RASTER, context) 

        load_layers = self.parameterAsBool(parameters, self.LOAD_LAYERS, context) 

        gpkg_path = self.parameterAsFileOutput(parameters, self.OUTPUT, context)

        # Run your solver
        feedback.pushInfo("Running pipeflow solver…")

        network_skeleton, network_xyz_layer = create_network_xyz_layer(pipe_results_layer=pipe_results_layer,chainage=chainage,raster_layer=raster_layer,load_layers=load_layers, feedback=feedback)

        processing.run("native:package", 
                    {'LAYERS':[network_skeleton, network_xyz_layer],
                     'OUTPUT':gpkg_path,
                     'OVERWRITE':False,
                     'SAVE_STYLES':True,
                     'SAVE_METADATA':True,
                     'SELECTED_FEATURES_ONLY':False,
                     'EXPORT_RELATED_LAYERS':False}
                   )

        return {}
        
    def name(self):
        return 'beggs_brill_skeleton'

    def displayName(self):
        return self.tr('Beggs and Brill Network Skeleton')

    def group(self):
        return self.tr(self.groupId())

    def groupId(self):
        return 'Beggs and Brill'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def shortHelpString(self):
        return self.tr("""
    Beggs and Brill based solver for calculating pressures from flowrates for multiphase services.
    
    Start by running a single-phase pandapipes pipeflow for network with desired fluid.
    
    This algorithm will take the pipe results layer as well as a chosen Digital Elevation Model to create a network skeleton.
    
    Once algorithm is complete, run "Beggs and Brill Pipe Flow".

    """)

    def createInstance(self):
        return BeggsBrillNetworkSkeleton()

class BeggsBrillPipeFlow(QgsProcessingAlgorithm):

    NETWORK_LAYER = 'NETWORK_LAYER'
    XYZ_LAYER = 'XYZ_LAYER'
    JUNCTION_LAYER = 'JUNCTION_LAYER'
    GRID_LAYER = 'GRID_LAYER'
    LIQUID_DENSITY = 'LIQUID_DENSITY'
    GAS_DENSITY = 'GAS_DENSITY'
    LIQUID_VISCOSITY = 'LIQUID_VISCOSITY'
    GAS_VISCOSITY = 'GAS_VISCOSITY'
    GAS_FRACTION = 'GAS_FRACTION'
    SURFACE_TENSION = 'SURFACE_TENSION'
    LOAD_LAYERS = 'LOAD_LAYERS'
    OUTPUT = 'OUTPUT'

    def initAlgorithm(self, config):

        # Input line layer
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.NETWORK_LAYER,
                self.tr('Select Network Skeleton Layer'),
                [QgsProcessing.TypeVectorLine]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.XYZ_LAYER,
                self.tr('Select Skeleton XYZ Layer'),
                [QgsProcessing.TypeVectorPoint]
            )
        )
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.JUNCTION_LAYER,
                self.tr('Select Junction Layer'),
                [QgsProcessing.TypeVectorPoint]
            )
        )
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.GRID_LAYER,
                self.tr('Select Grid Layer'),
                [QgsProcessing.TypeVector]
            )
        )
        
        self.addParameter(
            QgsProcessingParameterNumber(
                self.LIQUID_DENSITY, 'Liquid Density',
                type=QgsProcessingParameterNumber.Double,
                minValue=0, maxValue=100000, defaultValue=998
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.GAS_DENSITY, 'Gas Density',
                type=QgsProcessingParameterNumber.Double,
                minValue=0, maxValue=100000, defaultValue=0.65
            )
        )
        
        self.addParameter(
            QgsProcessingParameterNumber(
                self.LIQUID_VISCOSITY, 'Liquid Viscosity',
                type=QgsProcessingParameterNumber.Double,
                minValue=0, maxValue=100000, defaultValue=0.001
            )
        )
        
        self.addParameter(
            QgsProcessingParameterNumber(
                self.GAS_VISCOSITY, 'Gas Viscosity',
                type=QgsProcessingParameterNumber.Double,
                minValue=0, maxValue=100000, defaultValue=0.000002
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.GAS_FRACTION, 'Gas Fraction',
                type=QgsProcessingParameterNumber.Double,
                minValue=0, maxValue=1, defaultValue=0.5
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.SURFACE_TENSION, 'Surface Tension',
                type=QgsProcessingParameterNumber.Double,
                minValue=0, maxValue=1, defaultValue=0.072
            )
        )

        self.addParameter(
            QgsProcessingParameterBoolean(
                self.LOAD_LAYERS, 'Load Layers?',
                defaultValue=True
            )
        )

        # Output
        self.addParameter(QgsProcessingParameterFileDestination(
                self.OUTPUT,
                'Output GeoPackage',
                fileFilter='GeoPackage (*.gpkg)'
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        
        network_skeleton = self.parameterAsVectorLayer(parameters, self.NETWORK_LAYER, context)
        network_xyz = self.parameterAsVectorLayer(parameters, self.XYZ_LAYER, context)
        
        grid_layer = self.parameterAsVectorLayer(parameters, self.GRID_LAYER, context)
        junction_layer = self.parameterAsVectorLayer(parameters, self.JUNCTION_LAYER, context)
        
        gas_density = self.parameterAsDouble(parameters, self.GAS_DENSITY, context)
        gas_viscosity = self.parameterAsDouble(parameters, self.GAS_VISCOSITY, context)
        liquid_density = self.parameterAsDouble(parameters, self.LIQUID_DENSITY, context)
        liquid_viscosity = self.parameterAsDouble(parameters, self.LIQUID_VISCOSITY, context)
        surf_tens = self.parameterAsDouble(parameters, self.SURFACE_TENSION, context)
        gas_fraction = self.parameterAsDouble(parameters, self.GAS_FRACTION, context)
        
        load_layer = self.parameterAsBool(parameters, self.LOAD_LAYERS, context)
        
        gpkg_path = self.parameterAsFileOutput(parameters,self.OUTPUT,context)

        # Run your tee junction pipeline
        result_layers = run_beggs_brill_pipeflow(network_skeleton, network_xyz,
                             grid_layer, junction_layer,
                             gas_density,gas_viscosity,
                             liquid_density, liquid_viscosity,
                             surf_tens, gas_fraction,load_layer)
        
        processing.run("native:package", 
                    {'LAYERS':result_layers,
                     'OUTPUT':gpkg_path,
                     'OVERWRITE':False,
                     'SAVE_STYLES':True,
                     'SAVE_METADATA':True,
                     'SELECTED_FEATURES_ONLY':False,
                     'EXPORT_RELATED_LAYERS':False}
                   )

        return {}
        
    def name(self):
        return 'beggs_brill_pipe_flow'

    def displayName(self):
        return self.tr('Beggs and Brill Pipe Flow')

    def group(self):
        return self.tr(self.groupId())

    def groupId(self):
        return 'Beggs and Brill'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def shortHelpString(self):
        return self.tr("""
    Beggs and Brill based solver for calculating pressures from flowrates for multiphase services.
    
    Start by following procedure outlined in "Beggs and Brill Network Skeleton" algorithm.
    
    Once complete, select grid layer & junction layer to retrieve network pressures.
    
    An upated junction and pipe layer will be returned.
    """)

    def createInstance(self):
        return BeggsBrillPipeFlow()