# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MaterialTakeOffBuilderDockWidget
                                 A QGIS plugin
 A plugin to help develop Material Take-Offs and Equipment Lists for pipeline projects.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-01
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Thomas Raj
        email                : t.suraj.raj@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

from qgis.core import QgsMapLayerProxyModel, QgsProject, QgsField, QgsVectorLayer, QgsEditorWidgetSetup, QgsDefaultValue, QgsMapLayer, QgsWkbTypes

from qgis.gui import QgsFileWidget

from PyQt5.QtWidgets import QTreeWidgetItem, QListWidget, QMessageBox
from qgis.PyQt.QtCore import Qt, QVariant

import pandas as pd

from .logic.mto_builder import *
from .logic.additional_fittings import *

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'material_takeoff_builder_dockwidget_base.ui'))


class MaterialTakeOffBuilderDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(MaterialTakeOffBuilderDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        # Combo Boxes
        self.mlcbFeatureLayer.setFilters(QgsMapLayerProxyModel.PointLayer)

        # Tree Widgets
        # Network Components Tree Widget
        self.populate_pipeline_layer_tree()
        self.twPipelineLayers.setAlternatingRowColors(True)

        # Connect signals
        QgsProject.instance().layersAdded.connect(self.on_layers_changed)
        QgsProject.instance().layersRemoved.connect(self.on_layers_changed)
        QgsProject.instance().layerTreeRoot().nameChanged.connect(self.on_layers_changed)

        # File Widget
        self.fwAssemblyList.setStorageMode(QgsFileWidget.GetDirectory)
        self.fwAssemblyList.setStorageMode(QgsFileWidget.GetFile)
        self.fwAssemblyList.setFilter("Excel files (*.xlsx *.xls)")
        
        # Line Edit
        self.leSheetName.setText('Assembly List')
        
        # Buttons
        self.pbCorridorSummary.clicked.connect(self.on_pipe_corridor_summary_to_clipboard_clicked)
        self.pbLoadCorridorSummaryLayer.clicked.connect(self.on_load_pipe_corridor_summary_clicked)
        self.pbFittingsList.clicked.connect(self.on_generate_fittings_list_clicked)
        self.pbFittingsListSumLayer.clicked.connect(self.on_load_fittings_summary_clicked)
        self.pbCreateAdditionalFittingsLayer.clicked.connect(self.on_additional_fittings_list_clicked)
        
    # Non-User Input Functions
    def populate_pipeline_layer_tree(self):
        self.twPipelineLayers.clear()
        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() == QgsMapLayer.VectorLayer and layer.geometryType() == QgsWkbTypes.LineGeometry:
                item = QTreeWidgetItem([layer.name()])
                item.setCheckState(0, Qt.CheckState.Unchecked)
                self.twPipelineLayers.addTopLevelItem(item)

    def on_layers_changed(self):
        self.populate_pipeline_layer_tree()

    # Button Functions
    
    def on_pipe_corridor_summary_to_clipboard_clicked(self):
        
        pipe_layers = []

        for i in range(self.twPipelineLayers.topLevelItemCount()):
            item = self.twPipelineLayers.topLevelItem(i)
            if item.checkState(0) == Qt.Checked:
                component = item.text(0)  # Assuming the field name is in column 0
                pipe_layers.append(component)
        
        corridor_sum_df = corridor_summary(pipe_layers)
        
        corridor_sum_df.to_clipboard(index=False)
        
        QMessageBox.information(self, "Success!", "Corridor Summary copied to clipboard.")


    def on_load_pipe_corridor_summary_clicked(self):
        pipe_layers = []

        for i in range(self.twPipelineLayers.topLevelItemCount()):
            item = self.twPipelineLayers.topLevelItem(i)
            if item.checkState(0) == Qt.Checked:
                component = item.text(0)  # Assuming the field name is in column 0
                pipe_layers.append(component)
        
        corridor_sum_df = corridor_summary(pipe_layers)
        
        layer = load_df_as_layer(dataframe=corridor_sum_df,df_name='corridor_sum_df')
        
        layer.setName('Pipeline Corridor Summary')
        
        QgsProject.instance().addMapLayer(layer)

    def on_generate_fittings_list_clicked(self):
        
        
        assembly_list_path = self.fwAssemblyList.filePath()
        
        
        if assembly_list_path:
            assy_sheet = self.leSheetName.text()
            
            pipeline_feature_layer = self.mlcbFeatureLayer.currentLayer()
            
            fittings_list_df = generate_fittings_list(assembly_list_path,assy_sheet,pipeline_feature_layer)
            
            print(fittings_list_df.head())
            
            fittings_list_df.to_clipboard(index=False)
            
        else:
            QMessageBox.information(self, "Warning", "Assembly List hasn't been selected.")

    def on_load_fittings_summary_clicked(self):
        assembly_list_path = self.fwAssemblyList.filePath()
        
        
        if assembly_list_path:
            assy_sheet = self.leSheetName.text()
            
            pipeline_feature_layer = self.mlcbFeatureLayer.currentLayer()
            
            fittings_list_df = generate_fittings_list(assembly_list_path,assy_sheet,pipeline_feature_layer)
            
            print(fittings_list_df.head())
            
            layer = load_df_as_layer(dataframe=fittings_list_df,df_name='fittings_list_df')
        
            layer.setName('Fittings List')
            
            QgsProject.instance().addMapLayer(layer)
            
        else:
            QMessageBox.information(self, "Warning", "Assembly List hasn't been selected.")

    def on_additional_fittings_list_clicked(self):
        
        pipeline_feature_layer = self.mlcbFeatureLayer.currentLayer()
        
        additional_fittings = create_additional_fitting_layer(pipeline_feature_layer)
        
        additional_fittings.setName('Additional Fittings List')
        
        QgsProject.instance().addMapLayer(additional_fittings)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
