# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PandapipesForQGIS
                                 A QGIS plugin
 A pipe network modelling tool that can abstract models from GIS layers.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-14
        copyright            : (C) 2026 by Thomas Raj
        email                : lemungineer@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PandapipesForQGIS class from file PandapipesForQGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pipeline_engineer import PipelineEngineer
    return PipelineEngineer(iface)
