# -*- coding: utf-8 -*-

"""
/***************************************************************************
 PipelineEngineer
                                 A QGIS plugin
 A collection of Pipeline Engineering Tools.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-06
        copyright            : (C) 2025 by Pipeline Engineer
        email                : info@pipelineengineer.com.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Pipeline Engineer'
__date__ = '2025-12-06'
__copyright__ = '(C) 2025 by Pipeline Engineer'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsProcessingProvider
from .algorithms.material_takeoff.material_takeoff_algs import *
from .algorithms.network_cleanup.network_cleanup_algs import *
from .algorithms.pandapipes_for_qgis.pandapipes_for_qgis_algs import *
from .algorithms.fluids.fluid_algs import *
from .algorithms.beggs_brill.beggs_brill_algs import *

try:
    import pandapipes
    pandapipes_avail = True
except:
    pandapipes_avail = False

class PipelineEngineerProvider(QgsProcessingProvider):

    def __init__(self):
        """
        Default constructor.
        """
        QgsProcessingProvider.__init__(self)

    def unload(self):
        """
        Unloads the provider. Any tear-down steps required by the provider
        should be implemented here.
        """
        pass

    def loadAlgorithms(self):
        """
        Loads all algorithms belonging to this provider.
        """

        # Network Cleanup Algorithms
        self.addAlgorithm(disjointCheckAlgorithm())
        self.addAlgorithm(recursiveSelectionAlgorithm())
        self.addAlgorithm(loopCheckingAlgorithm())

        # Material Takeoff Algorithms
        self.addAlgorithm(TeeJunctionsAlgorithm())
        self.addAlgorithm(BendsAlgorithm())
        self.addAlgorithm(FourWayUnionsAlgorithm())
        self.addAlgorithm(PipeSummariserAlgorithm())
        self.addAlgorithm(PointSummariserAlgorithm())
        self.addAlgorithm(AttachLineDetailsAlgorithm())
        
        # Pandapipes Algs
        if pandapipes_avail:
            
            # Fluids
            self.addAlgorithm(AddFluidValueToLayer())
            
            # Pandapipes
            self.addAlgorithm(runPipeFlowAlgorithm())
            
            # Beggs and Brill
            #self.addAlgorithm(BeggsBrillNetworkSkeleton())
            #self.addAlgorithm(BeggsBrillPipeFlow())
            self.addAlgorithm(runBeggsBrillPipeFlowAlgorithm())
            

    def id(self):
        """
        Returns the unique provider id, used for identifying the provider. This
        string should be a unique, short, character only string, eg "qgis" or
        "gdal". This string should not be localised.
        """
        return 'Pipeline Engineer'

    def name(self):
        """
        Returns the provider name, which is used to describe the provider
        within the GUI.

        This string should be short (e.g. "Lastools") and localised.
        """
        return self.tr('Pipeline Engineer')

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        return QgsProcessingProvider.icon(self)

    def longName(self):
        """
        Returns the a longer version of the provider name, which can include
        extra details such as version numbers. E.g. "Lastools LIDAR tools
        (version 2.2.1)". This string should be localised. The default
        implementation returns the same string as name().
        """
        return self.name()
