# -*- coding: utf-8 -*-

"""
/***************************************************************************
 PipelineEngineer
                                 A QGIS plugin
 A collection of Pipeline Engineering Tools.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-06
        copyright            : (C) 2025 by Pipeline Engineer
        email                : info@pipelineengineer.com.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Pipeline Engineer'
__date__ = '2025-12-06'
__copyright__ = '(C) 2025 by Pipeline Engineer'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .pipeline_engineer_provider import PipelineEngineerProvider

from qgis.PyQt.QtWidgets import QAction, QMenu
from qgis.utils import iface

from .ui.pp_components.pp_network_component_dialog import *

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class PipelineEngineerPlugin(object):

    def __init__(self, iface):
        # Save reference to the QGIS interface
        self.iface = iface

        self.provider = None
        self.action = None
        self.dialog = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = PipelineEngineerProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        # Initialize processing provider
        self.initProcessing()

        # Adding Pipeline Engineer Menu
        self.menu = self.iface.mainWindow().menuBar().addMenu("Pipeline Engineer")

        # PANDAPIPES
        # Submenu
        pandapipes_for_qgis = QMenu("Pandapipes for QGIS", self.iface.mainWindow())
        self.menu.addMenu(pandapipes_for_qgis)

        # Add separators
        self.menu.addSeparator()

        # Add menu items
        action1 = QAction("Create Network Component", parent=self.menu)
        action1.triggered.connect(self.launch_network_dialog)  # Connect to proper method
        pandapipes_for_qgis.addAction(action1)


    def launch_network_dialog(self):
        self.comp_dialog = PPComponentDialog(self.iface.mainWindow())
        self.comp_dialog.show()

    def launch_pipeflow_dialog(self):
        self.comp_dialog = PPRunPipeFlowDialog(self.iface.mainWindow())
        self.comp_dialog.show()

    def launch_beggs_brill_dialog(self):
        self.comp_dialog = BeggsBrillDialog(self.iface.mainWindow())
        self.comp_dialog.show()

    def unload(self):
        # Remove processing provider
        QgsApplication.processingRegistry().removeProvider(self.provider)

        # Remove the Pipeline Engineer menu if it exists
        if hasattr(self, 'menu') and self.menu:
            self.iface.mainWindow().menuBar().removeAction(self.menu.menuAction())
            self.menu = None

    def showDialog(self):
        # Instantiate and show your dialog
        if not self.dialog:
            self.dialog = PPComponentDialog(iface.mainWindow())
        self.dialog.show()
        self.dialog.raise_()
        self.dialog.activateWindow()

