# -*- coding: utf-8 -*-

"""
/***************************************************************************
 PipelineEngineer
                                 A QGIS plugin
 A collection of Pipeline Engineering Tools.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-06
        copyright            : (C) 2025 by Pipeline Engineer
        email                : info@pipelineengineer.com.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Pipeline Engineer'
__date__ = '2025-12-06'
__copyright__ = '(C) 2025 by Pipeline Engineer'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (
    QgsProcessing,
    QgsFeatureSink,
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterField,
    QgsFeatureRequest,
    QgsProcessingParameterNumber,
    QgsProcessingParameterEnum,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterExpression
)

from .logic.tee_junctions import summarise_tees
from .logic.bends import summarise_bends
from .logic.four_way_unions import summarise_four_way_unions


class TeeJunctionsAlgorithm(QgsProcessingAlgorithm):

    INPUT = 'INPUT'
    OUTPUT = 'OUTPUT'
    ID_FIELD = 'ID_FIELD'
    ID_EXPRESSION = 'ID_EXPRESSION'

    def initAlgorithm(self, config):

        # Input line layer
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Input layer'),
                [QgsProcessing.TypeVectorLine]
            )
        )

        # Field to use as ID (e.g. name, corridor ID, pipe ID, etc)
        self.addParameter(
            QgsProcessingParameterField(
                self.ID_FIELD,
                self.tr('ID field'),
                parentLayerParameterName=self.INPUT,
                type=QgsProcessingParameterField.Any
            )
        )

        self.addParameter(
            QgsProcessingParameterExpression(
                self.ID_EXPRESSION,
                'ID Expression',
                defaultValue="CONCAT('JUNCTION_',LPAD($id,5,'00000'))",
                parentLayerParameterName=None  # or a layer parameter ID
            )
        )


        # Output
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Tees')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):

        # Retrieve layer source
        source = self.parameterAsSource(parameters, self.INPUT, context)

        # Convert to a materialised QgsVectorLayer (so it can be processed normally)
        layer = source.materialize(QgsFeatureRequest())

        # Retrieve ID field selected by user
        id_field = self.parameterAsString(parameters, self.ID_FIELD, context)
        
        id_expression = self.parameterAsExpression(parameters, self.ID_EXPRESSION, context)

        feedback.pushInfo(f"Using ID field: {id_field}")

        # Run your tee junction pipeline
        result_layer = summarise_tees(layer, id_field=id_field,id_expression=id_expression)

        # Create sink with the fields, geometry type and CRS of the output layer
        sink, dest_id = self.parameterAsSink(
            parameters,
            self.OUTPUT,
            context,
            result_layer.fields(),
            result_layer.wkbType(),
            result_layer.sourceCrs()
        )

        # Add resulting features to sink
        for f in result_layer.getFeatures():
            if feedback.isCanceled():
                break
            sink.addFeature(f, QgsFeatureSink.FastInsert)

        return {self.OUTPUT: dest_id}

    def name(self):
        return 'tee_junctions'

    def displayName(self):
        return self.tr('Tees')

    def group(self):
        return self.tr(self.groupId())

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def shortHelpString(self):
        return self.tr("""
    Indentifies all tee branches within a line layer.
    
    Includes angle between branch and header.
    
    ID expression of tees can be modified to better suit user's needs.
    """)

    def createInstance(self):
        return TeeJunctionsAlgorithm()

class BendsAlgorithm(QgsProcessingAlgorithm):

    INPUT = 'INPUT'
    OUTPUT = 'OUTPUT'
    ID_FIELD = 'ID_FIELD'
    ID_EXPRESSION = 'ID_EXPRESSION'

    def initAlgorithm(self, config):

        # Input line layer
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Input layer'),
                [QgsProcessing.TypeVectorLine]
            )
        )

        # Field to use as ID (e.g. name, corridor ID, pipe ID, etc)
        self.addParameter(
            QgsProcessingParameterField(
                self.ID_FIELD,
                self.tr('ID field'),
                parentLayerParameterName=self.INPUT,
                type=QgsProcessingParameterField.Any
            )
        )

        # Minimum Bend Angle
        self.addParameter(
            QgsProcessingParameterNumber(
                'MIN_ANGLE',
                self.tr('Minimum bend angle (degrees)'),
                type=QgsProcessingParameterNumber.Double,
                minValue=0.0,
                maxValue=180.0,
                defaultValue=30.0     # choose your own default
            )
        )

        self.addParameter(
            QgsProcessingParameterExpression(
                self.ID_EXPRESSION,
                'ID Expression',
                defaultValue="CONCAT('BEND_',LPAD($id,5,'00000'))",
                parentLayerParameterName=None  # or a layer parameter ID
            )
        )

        # Output
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Bends')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):

        # Retrieve layer source
        source = self.parameterAsSource(parameters, self.INPUT, context)

        # Convert to a materialised QgsVectorLayer (so it can be processed normally)
        layer = source.materialize(QgsFeatureRequest())

        # Retrieve ID field selected by user
        id_field = self.parameterAsString(parameters, self.ID_FIELD, context)

        # Retrieve Minimum Bend Angle
        min_bend_angle = self.parameterAsDouble(parameters, 'MIN_ANGLE', context)
        
        id_expression = self.parameterAsExpression(parameters, self.ID_EXPRESSION, context)

        feedback.pushInfo(f"Using ID field: {id_field}")
        feedback.pushInfo(f"Minimum bend angle: {min_bend_angle}")

        # Run your tee junction pipeline
        result_layer = summarise_bends(layer, id_field=id_field,min_bend_angle=min_bend_angle,feature_id_exp=id_expression)

        # Create sink with the fields, geometry type and CRS of the output layer
        sink, dest_id = self.parameterAsSink(
            parameters,
            self.OUTPUT,
            context,
            result_layer.fields(),
            result_layer.wkbType(),
            result_layer.sourceCrs()
        )

        # Add resulting features to sink
        for f in result_layer.getFeatures():
            if feedback.isCanceled():
                break
            sink.addFeature(f, QgsFeatureSink.FastInsert)

        return {self.OUTPUT: dest_id}

    def name(self):
        return 'bends'

    def displayName(self):
        return self.tr('Bends')

    def group(self):
        return self.tr(self.groupId())

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def shortHelpString(self):
        return self.tr("""
    Indentifies all bends within a line layer.
    
    Bends with an angle smaller than the specified Minimum Bend Angle will be filtered out.
    
    ID expression of bends can be modified to better suit user's needs.
    """)

    def createInstance(self):
        return BendsAlgorithm()

class FourWayUnionsAlgorithm(QgsProcessingAlgorithm):

    INPUT = 'INPUT'
    OUTPUT = 'OUTPUT'
    ID_FIELD = 'ID_FIELD'
    ID_EXPRESSION = 'ID_EXPRESSION'

    def initAlgorithm(self, config):

        # Input line layer
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Input layer'),
                [QgsProcessing.TypeVectorLine]
            )
        )

        # Field to use as ID (e.g. name, corridor ID, pipe ID, etc)
        self.addParameter(
            QgsProcessingParameterField(
                self.ID_FIELD,
                self.tr('ID field'),
                parentLayerParameterName=self.INPUT,
                type=QgsProcessingParameterField.Any
            )
        )

        self.addParameter(
            QgsProcessingParameterExpression(
                self.ID_EXPRESSION,
                'ID Expression',
                defaultValue="CONCAT('UNION_',LPAD($id,5,'00000'))",
                parentLayerParameterName=None  # or a layer parameter ID
            )
        )

        # Output
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Four-Way Unions')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):

        # Retrieve layer source
        source = self.parameterAsSource(parameters, self.INPUT, context)

        # Convert to a materialised QgsVectorLayer (so it can be processed normally)
        layer = source.materialize(QgsFeatureRequest())

        # Retrieve ID field selected by user
        id_field = self.parameterAsString(parameters, self.ID_FIELD, context)

        id_expression = self.parameterAsExpression(parameters, self.ID_EXPRESSION, context)

        feedback.pushInfo(f"Using ID field: {id_field}")

        # Run your tee junction pipeline
        result_layer = summarise_four_way_unions(layer, id_field=id_field,id_expression=id_expression)

        # Create sink with the fields, geometry type and CRS of the output layer
        sink, dest_id = self.parameterAsSink(
            parameters,
            self.OUTPUT,
            context,
            result_layer.fields(),
            result_layer.wkbType(),
            result_layer.sourceCrs()
        )

        # Add resulting features to sink
        for f in result_layer.getFeatures():
            if feedback.isCanceled():
                break
            sink.addFeature(f, QgsFeatureSink.FastInsert)

        return {self.OUTPUT: dest_id}

    def name(self):
        return 'four_way_unions'

    def displayName(self):
        return self.tr('Four Way Unions')

    def group(self):
        return self.tr(self.groupId())

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def shortHelpString(self):
        return self.tr("""
    Indentifies all four-way unions within a line layer.
    
    ID expression of unions can be modified to better suit user's needs.
    """)

    def createInstance(self):
        return FourWayUnionsAlgorithm()
    
