# -*- coding: utf-8 -*-

"""
/***************************************************************************
 PipelineEngineer
                                 A QGIS plugin
 A collection of Pipeline Engineering Tools.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-06
        copyright            : (C) 2025 by Pipeline Engineer
        email                : info@pipelineengineer.com.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Pipeline Engineer'
__date__ = '2025-12-06'
__copyright__ = '(C) 2025 by Pipeline Engineer'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (
    QgsProcessing,
    QgsFeatureSink,
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterField,
    QgsFeatureRequest,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterNumber,
    QgsProcessingParameterVectorLayer
)

from .logic.disjoint_check import disjoint_check
from .logic.recursive_selection import recursive_selection
from .logic.loop_check import loop_checker

class disjointCheckAlgorithm(QgsProcessingAlgorithm):

    INPUT = 'INPUT'
    CHECK_SELECTED = 'CHECK_SELECTED'
    OUTPUT = 'OUTPUT'

    def initAlgorithm(self, config):

        # Input line layer
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT,
                self.tr('Input layer'),
                [QgsProcessing.TypeVectorLine]
            )
        )

        self.addParameter(
            QgsProcessingParameterBoolean(
                'CHECK_SELECTED',           # internal parameter name
                self.tr('Disjoint Check Selected Feature?'),  # label shown in GUI
                defaultValue=False         # optional, default True or False
            )
        )


    def processAlgorithm(self, parameters, context, feedback):
        # Use the actual project layer
        layer = self.parameterAsVectorLayer(parameters, self.INPUT, context)

        # Retrieve ID field
        check_selected_feature = self.parameterAsBool(parameters, self.CHECK_SELECTED, context)

        #feedback.pushInfo(f"Using ID field: {id_field}")

        # Run the selection function
        disjoint_check(layer=layer, selected_features=check_selected_feature)

        # Return the original layer as output (or create a dummy output if needed)
        return {self.OUTPUT: layer.id()}


    def name(self):
        return 'disjoint_check'

    def displayName(self):
        return self.tr('Disjoint Check')

    def group(self):
        return self.tr(self.groupId())

    def groupId(self):
        return 'Network Cleanup'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def shortHelpString(self):
        return self.tr("""
    This algorithm selects all lines that are connected to one another.
                       
    A starter line (or lines) can be selected to begin this process or the algorithm can choose a line at random within the network.
                       
    """)

    def createInstance(self):
        return disjointCheckAlgorithm()

class recursiveSelectionAlgorithm(QgsProcessingAlgorithm):

    INPUT = 'INPUT'
    CHECK_SELECTED = 'CHECK_SELECTED'
    OUTPUT = 'OUTPUT'

    def initAlgorithm(self, config):

        # Input line layer
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT,
                self.tr('Input layer'),
                [QgsProcessing.TypeVectorLine]
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        # Use the actual project layer
        layer = self.parameterAsVectorLayer(parameters, self.INPUT, context)

        #feedback.pushInfo(f"Using ID field: {id_field}")

        # Run the selection function
        recursive_selection(edges=layer)

        # Return the original layer as output (or create a dummy output if needed)
        return {self.OUTPUT: layer.id()}


    def name(self):
        return 'recursive_selection'

    def displayName(self):
        return self.tr('Recursive Selection')

    def group(self):
        return self.tr(self.groupId())

    def groupId(self):
        return 'Network Cleanup'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def shortHelpString(self):
        return self.tr("""
    This purpose of this algorithm is to determine which lines feed into the selected line.
                       
    This is accomplished by find which lines end where the selected line starts.
                       
    This process is repeated until no more lines are no more lines feeding into the selected part of the network are found.
    """)

    def createInstance(self):
        return recursiveSelectionAlgorithm()

class loopCheckingAlgorithm(QgsProcessingAlgorithm):

    INPUT = 'INPUT'
    OUTPUT = 'OUTPUT'
    ID_FIELD = 'ID_FIELD'

    def initAlgorithm(self, config):

        # Input line layer
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT,
                self.tr('Input layer'),
                [QgsProcessing.TypeVectorLine]
            )
        )

        # Field to use as ID (e.g. name, corridor ID, pipe ID, etc)
        self.addParameter(
            QgsProcessingParameterField(
                self.ID_FIELD,
                self.tr('Loop Field'),
                parentLayerParameterName=self.INPUT,
                type=QgsProcessingParameterField.Any
            )
        )

        # Output
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Loops')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        # Use the actual project layer
        layer = self.parameterAsVectorLayer(parameters, self.INPUT, context)

        id_field = self.parameterAsString(parameters, self.ID_FIELD, context)

        #feedback.pushInfo(f"Using ID field: {id_field}")

        # Run your tee junction pipeline
        result_layer = loop_checker(layer=layer, loop_field=id_field)

        # Create sink with the fields, geometry type and CRS of the output layer
        sink, dest_id = self.parameterAsSink(
            parameters,
            self.OUTPUT,
            context,
            result_layer.fields(),
            result_layer.wkbType(),
            result_layer.sourceCrs()
        )

        # Add resulting features to sink
        for f in result_layer.getFeatures():
            if feedback.isCanceled():
                break
            sink.addFeature(f, QgsFeatureSink.FastInsert)

        return {self.OUTPUT: dest_id}


    def name(self):
        return 'loop_check'

    def displayName(self):
        return self.tr('Loop Check')

    def group(self):
        return self.tr(self.groupId())

    def groupId(self):
        return 'Network Cleanup'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def shortHelpString(self):
        return self.tr("""
    This purpose of this algorithm is to ensure that all loops within a system are fully connected.
                       
    Start by creating an empty column in your network layer. Fill that column with a value (any value will do) for any line that is part of a loop.
                       
    Once done, run this algorithm and a layer will be returned. Each line in this layer should be a continuous until it meets another line.
    
    If they aren't continuous, there's a discontinuity in the loops within the network, fix any identifed areas and repeat until all loops are interconnected.
    """)

    def createInstance(self):
        return loopCheckingAlgorithm()