# -*- coding: utf-8 -*-

"""
/***************************************************************************
 PandaPipesForQGIS
                                 A QGIS plugin
 A fluid modelling tool that can abstract models from GIS layers.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-14
        copyright            : (C) 2026 by Thomas Raj
        email                : lemungineer@gmail.com.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Thomas Raj'
__date__ = '2026-02-14'
__copyright__ = '(C) 2026 by Thomas Raj'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsProcessingProvider

# Fluid Modelling

import os

from qgis.PyQt.QtGui import QIcon

#try:
import pandapipes
from .algorithms.fluid_modelling.pipeflow.pipeflow_alg import runPipeFlowAlgorithm
#from .algorithms.fluid_modelling.beggs_brill.beggs_brill_alg import runBeggsBrillPipeFlowAlgorithm
from .algorithms.fluid_modelling.fluids.fluid_algs import AddFluidValueToLayer
from .algorithms.fluid_modelling.two_phase_flow.two_phase_flow_alg import TwoPhaseModelAlgorithm
#from .algorithms.fluid_modelling.homogeneous_model_downstream.downstream_homogenous_model_alg import DownstreamHomogenousTwoPhaseModelAlgorithm
from .algorithms.fluid_modelling.update_flow_rates.update_flow_rates_alg import updateFlowRatesAlgorithm
#except:
#    pass

class PandaPipesForQGISProvider(QgsProcessingProvider):

    def __init__(self):
        """
        Default constructor.
        """
        QgsProcessingProvider.__init__(self)

    def unload(self):
        """
        Unloads the provider. Any tear-down steps required by the provider
        should be implemented here.
        """
        pass

    def loadAlgorithms(self):
        """
        Loads all algorithms belonging to this provider.
        """
        self.addAlgorithm(runPipeFlowAlgorithm())
        #self.addAlgorithm(runBeggsBrillPipeFlowAlgorithm())
        self.addAlgorithm(AddFluidValueToLayer())
        self.addAlgorithm(TwoPhaseModelAlgorithm())
        #self.addAlgorithm(DownstreamHomogenousTwoPhaseModelAlgorithm())
        self.addAlgorithm(updateFlowRatesAlgorithm())
        # add additional algorithms here
        # self.addAlgorithm(MyOtherAlgorithm())

    def id(self):
        """
        Returns the unique provider id, used for identifying the provider. This
        string should be a unique, short, character only string, eg "qgis" or
        "gdal". This string should not be localised.
        """
        return 'pandapipes_for_qgis'

    def name(self):
        """
        Returns the provider name, which is used to describe the provider
        within the GUI.

        This string should be short (e.g. "Lastools") and localised.
        """
        return self.tr('Fluid Modelling')

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        script_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        icon_path = os.path.join(script_dir,'icons','two_phase_flow.png')
        return QIcon(icon_path)

    def longName(self):
        """
        Returns the a longer version of the provider name, which can include
        extra details such as version numbers. E.g. "Lastools LIDAR tools
        (version 2.2.1)". This string should be localised. The default
        implementation returns the same string as name().
        """
        return self.name()
